### ISSUE TITLE
Adding support for spaces in table names

### ISSUE THREAD

**Issue by klamann** [pavlov99/mdb-export-all#2]
Neat script, thanks for providing it!

In case you ever need to handle databases that have spaces in table names (I know, this is horrible...), the loop over table names will fail (because whitespace is the default bash delimiter).

Just change the output of `mdb-tables` to newline-separated by adding the `-1` flag and change bash's default separator to newline with `IFS=$'\n'`, then it will work even for tables with weird names. Here's the relevant code snippet:

    IFS=$'\n'
    for table in $(mdb-tables -1 "$fullfilename"); do

**Comment by pavlov99** [comment]
Hi, @klamann 

Thank you for your suggestion! Updated the code: https://github.com/pavlov99/mdb-export-all/commit/e3bc6495d4bf2f845bbdefe3c5cf2e5351436717
